# Generated by Django 3.2 on 2021-05-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('childhood', 'Infância'), ('adolescence', 'Adolecência'), ('adult', 'Adulto')], max_length=15)),
                ('tip', models.CharField(max_length=255)),
            ],
        ),
    ]
