# Generated by Django 3.2 on 2021-05-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='tip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
