# Generated by Django 3.2 on 2021-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1_movies',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_movies',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_champion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
