# Generated by Django 3.2 on 2021-04-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0002_auto_20210415_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(default=1, to='ticTacToe.Player'),
        ),
    ]
